# Generated by Django 3.2.8 on 2022-01-22 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centre', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('favorited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited', to='centre.shoppingcentre')),
                ('favorited_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_for', to='centre.shoppingcentre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.myuser')),
            ],
            options={
                'unique_together': {('favorited', 'favorited_for', 'user')},
            },
        ),
    ]
