# Generated by Django 3.2.8 on 2022-01-25 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0001_initial'),
        ('favorited', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('favorited',)},
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='favorited_for',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
    ]
